name: Test

on:
  pull_request:
    branches: [ "main" ]
  paths-ignore:
    - README.md

jobs:
  build:  
    name: Test
    strategy:
      fail-fast: false    
      matrix:
        os: [macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode 15
        run: sudo xcode-select -s /Applications/Xcode_15.0.app
        
      - name: Test
        run: swift test
